name: Build

on: [push, repository_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # Checkout this repository
    - name: Checkout this repository
      uses: actions/checkout@v2

    # Setup DotNet CLI
    - uses: actions/setup-dotnet@v1
      name: Setup DotNet CLI
      with:
        dotnet-version: '3.1.x'

    # Checkout Edgar-DotNet master branch
    - uses: actions/checkout@v2
      name: Checkout Edgar-DotNet master branch
      with:
        repository: OndrejNepozitek/Edgar-DotNet
        # ref: master
        ref: dev
        path: src/master/checkout

    # Checkout Edgar-DotNet dev branch
    - uses: actions/checkout@v2
      name: Checkout Edgar-DotNet dev branch
      with:
        repository: OndrejNepozitek/Edgar-DotNet
        ref: dev
        path: src/dev/checkout

    # Build master
    - name: Build master
      run: dotnet build src/master/checkout/Edgar/Edgar.csproj

    # Build dev
    - name: Build dev
      run: dotnet build src/dev/checkout/Edgar/Edgar.csproj

    # Copy dlls and xml comments
    - name: Copy dlls and xml comments
      run: |
        cp src/master/checkout/Edgar/bin/Debug/netstandard2.0/Edgar.dll src/master/Edgar.dll
        cp src/master/checkout/Edgar/bin/Debug/netstandard2.0/Edgar.xml src/master/Edgar.xml
        cp src/dev/checkout/Edgar/bin/Debug/netstandard2.0/Edgar.dll src/dev/Edgar.dll
        cp src/dev/checkout/Edgar/bin/Debug/netstandard2.0/Edgar.xml src/dev/Edgar.xml
        rm -r src/master/checkout
        rm -r src/dev/checkout
    
    # DocFx metadata
    - uses: OndrejNepozitek/docfx-action@master
      name: DocFx metadata
      with:
        args: metadata

    # Install node
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Install js-yaml
    - name: Install js-yaml
      run: npm install js-yaml

    # Run toc.js
    - name: Run toc.js
      run: sudo node toc.js

    # DocFx build
    - uses: OndrejNepozitek/docfx-action@master
      name: DocFx build
      with:
        args: build

    # Publish to Github Pages
    - uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}